language: php

php:
  - '7.2'
  - '7.3'
  - nightly

branches:
  only:
    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest --dev

script:
  - vendor/bin/phpcs

cache:
  directories:
    - $HOME/.composer/cache