language: php

php:
  - '7.2'
  - '7.3'

branches:
  only:
    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache