sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpcs
